[project]
name = "p21api"
version = "0.1.0"
description = ""
authors = [{ name = "tomt00001", email = "107521427+tomt00001@users.noreply.github.com" }]
requires-python = ">=3.12,<3.14"
readme = "README.md"
dependencies = [
    "requests>=2.32.3,<3",
    "petl>=1.7.15,<2",
    "pyqt6>=6.7.1,<7",
    "pydantic>=2.10.6,<3",
    "pydantic-settings>=2.7.1,<3",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13,<0.14",
    "ruff>=0.8.0,<0.9",
    "black>=24.8.0,<25",
    "ipython>=8.27.0,<9",
    "pyinstaller>=6.10.0,<7",
    "pytest>=8.3.4,<9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
src = ["./p21api", "./gui", "./reports", "./config", "./client"]
# Pyflakes, Pycodestyle, and isort
select = ["E", "F", "I", "T"]
# maybe need "E129"
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*migrations*",
]
per-file-ignores = {}

# Same as Black
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py311"
