[tool.poetry]
name = "p21api"
version = "0.1.0"
description = ""
authors = ["tomt00001 <107521427+tomt00001@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
requests = "^2.32.3"
petl = "^1.7.15"
pyqt6 = "^6.7.1"
pydantic = "^2.10.6"
pydantic-settings = "^2.7.1"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"
ruff = "^0.6.8"
black = "^24.8.0"
ipython = "^8.27.0"
pyinstaller = "^6.10.0"
pytest = "^8.3.4"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
src = ["./p21api", "./gui", "./reports", "./config", "./client"]
# Pyflakes, Pycodestyle, and isort
select = ["E", "F", "I", "T"]
# maybe need "E129"
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*migrations*",
]
per-file-ignores = {}

# Same as Black
line-length = 88

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py311"
