from typing import Any, Optional

from . import QWidget

class QDateEdit(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setCalendarPopup(self, enable: bool) -> None: ...
    def setDate(self, date: Any) -> None: ...
    def date(self) -> Any: ...
