from typing import Optional

from . import QWidget

class QDialog(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def setGeometry(self, x: int, y: int, w: int, h: int) -> None: ...
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    DialogCode: int
    Accepted: int
    Rejected: int
