from typing import Optional

from . import QWidget

class QListWidgetItem:
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setSelected(self, selected: bool) -> None: ...
    def text(self) -> str: ...
