from typing import Any, Optional

from . import QWidget

class QPushButton(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setDefault(self, is_default: bool) -> None: ...
    clicked: Any
