from typing import Optional

from . import QLayout, QWidget

class QVBoxLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def addLayout(self, layout: QLayout) -> None: ...
